let allMusic = [
  {
    name: "Bharatha Vedamuga",
    artist: "DSP",
    img: "prabhas-1",
    src: "prabhas-1",
  },
  {
    name: "Muvvala Navvakala",
    artist: "DSP",
    img: "prabhas-1",
    src: "prabhas-2",
  },
  {
    name: "Paravaledhu",
    artist: "Sekhar",
    img: "Manasara",
    src: "Manasara",
  },
  {
    name: "Pranaamam",
    artist: "DSP",
    img: "ntr-2",
    src: "ntr-2",
  },
  {
    name: "Apple Beauty",
    artist: "DSP",
    img: "ntr-2",
    src: "ntr-3",
  },
  {
    name: "Nee Selvadigi",
    artist: "DSP",
    img: "ntr-2",
    src: "ntr-4",
  },
  {
    name: "Shape-of-You",
    artist: "Ed Sheeran",
    img: "music-1",
    src: "music-1",
  },
  {
    name: "Let Me Down Slowly",
    artist: "Alec Benjamin",
    img: "music-3",
    src: "music-3",
  },
  {
    name: "Girls Like You",
    artist: "Maroon 5",
    img: "music-6",
    src: "music-6",
  },
  {
    name: "On My Way",
    artist: "Alan Walker",
    img: "music-7",
    src: "music-7",
  },
  {
    name: "Sorry",
    artist: "Justin Beiber",
    img: "music-8",
    src: "music-8",
  },
  {
    name: "Faded",
    artist: "Alan Walker",
    img: "music-10",
    src: "music-10",
  },
  {
    name: "Prema desham",
    artist: "Manisharma",
    img: "ntr-1",
    src: "ntr-1",
  },
  {
    name: "Bahubali",
    artist: "M M Keeravani",
    src: "B-1",
  },
  {
    name: "Bahubali",
    artist: "M M Keeravani",
    src: "B-2",
  },
  {
    name: "Bahubali",
    artist: "M M Keeravani",
    src: "B-3",
  },
  {
    name: "Bahubali",
    artist: "M M Keeravani",
    src: "B-4",
  },
  {
    name: "Bahubali",
    artist: "M M Keeravani",
    src: "B-5",
  },
  {
    name: "Bahubali",
    artist: "M M Keeravani",
    src: "B-6",
  },
  {
    name: "Bahubali",
    artist: "M M Keeravani",
    src: "B-7",
  },
  {
    name: "Bahubali",
    artist: "M M Keeravani",
    src: "B-8",
  },
];
